# Generated by Django 2.0.7 on 2022-05-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_summery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
